### ISSUE TITLE
apt_key returns 403 Forbidden when downloading OpenVPN GPG key

### ISSUE THREAD

**Issue by chroche** [sansible/openvpn#11]
apt_key fails when trying to download GPG key from OpenVPN web site:
```
fatal: [host]: FAILED! => {"changed": false, "failed": true, "msg": "Failed to download key at https://swupdate.openvpn.net/repos/repo-public.gpg: HTTP Error 403: Forbidden"}
```
This is an Ansible bug as reported [here](https://github.com/ansible/ansible/issues/22647).

A simple workaround is to donwnload the key from a GPH key server rather then from the OpenVPN website.

**Comment by lobsterdore** [comment]
Closed by #12
