### ISSUE TITLE
Add support for adding custom "push" settings

### ISSUE THREAD

**Issue by wojtek-oledzki** [sansible/openvpn#5]
**As a** Infrastructure Developer
**I want** push custom configuration to VPN clients
So that I can push custom "dhcp-option" config.

**Comment by lobsterdore** [comment]
There is an option that should cover this "openvpn.server_extra_options"

**Comment by wojtek-oledzki** [comment]
Yes there is :) 
https://github.com/sansible/openvpn/blob/e2fec5218b553df4ce87448070c08c8f294c84db/templates/server.conf.j2#L58-L60

I'm closing it down.
